"""
make_tables.py
--------------
Regenerates the manuscript tables (Table 1 latency, Table 2 network,
Table 3 provisioning/Ev, Table 5 SEI) as Markdown and CSV from the synthesised
inputs in data/published_benchmarks.json. Pure transformation of published
figures; no measurement.
"""
import json
import os
import csv
from compute_metrics import load_inputs, compute_elasticity_velocity, compute_sei

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "outputs")


def _write_csv(name, header, rows):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(header)
        w.writerows(rows)


def table1(data):
    d = data["database_latency"]
    header = ["Platform", "Consistency", "p50 Read (ms)", "p99 Read (ms)",
              "p99 Write (ms)", "Throughput Stability"]
    rows = [[p["platform"], p["consistency"], p["p50_read_ms"], p["p99_read_ms"],
             p["p99_write_ms"], p["throughput_stability"]] for p in d["platforms"]]
    _write_csv("table1_database_latency.csv", header, rows)
    vt = d["vendor_tuned_note"]
    note = (f"Note: YCSB Workload A basis. {vt['platform']} reaches "
            f"{vt['p99_read_ms']} ms p99 read only under {vt['condition']} "
            f"[{vt['source_ref']}]; reported separately.")
    return header, rows, note


def table2(data):
    header = ["Provider", "Network Tier", "US-East<->EU-West RTT (ms)",
              "Packet Loss (%)", "Jitter (ms)"]
    rows = [[p["platform"], p["tier"], p["rtt_useast_euwest_ms"],
             p["packet_loss_pct"], p["jitter_ms"]]
            for p in data["network_latency"]["platforms"]]
    _write_csv("table2_network_latency.csv", header, rows)
    return header, rows


def table3(data):
    ev = compute_elasticity_velocity(data["provisioning"])
    header = ["Platform", "Architecture", "Time to Ready (s)",
              "Ev (inst/s)", "Burst Failure Rate (%)"]
    rows = [[r["platform"], r["architecture"], r["time_to_ready_s"],
             r["ev_instances_per_s"], r["burst_failure_rate_pct"]] for r in ev]
    _write_csv("table3_provisioning_ev.csv", header, rows)
    return header, rows, ev


def table5(data, ev_rows):
    sei = compute_sei(ev_rows, data["cost_efficiency"])
    header = ["Platform", "Ev_norm", "rho", "C_norm", "SEI", "SEI*"]
    rows = [[r["platform"], r["ev_norm"], r["rho"], r["c_norm"],
             r["sei"], r["sei_star"]] for r in sei]
    _write_csv("table5_sei.csv", header, rows)
    return header, rows


def _md(title, header, rows, note=None):
    line = "| " + " | ".join(header) + " |"
    sep = "| " + " | ".join("---" for _ in header) + " |"
    body = "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in rows)
    out = f"### {title}\n\n{line}\n{sep}\n{body}\n"
    if note:
        out += f"\n*{note}*\n"
    return out


def main():
    data = load_inputs()
    h1, r1, note1 = table1(data)
    h2, r2 = table2(data)
    h3, r3, ev = table3(data)
    h5, r5 = table5(data, ev)

    md = ["# Reproduced Manuscript Tables (synthesised)\n",
          "Generated by `make_tables.py` from `data/published_benchmarks.json`.\n",
          _md("Table 1. Synthesised Database Latency Profiles", h1, r1, note1),
          _md("Table 2. Trans-Atlantic Network Latency (RTT)", h2, r2),
          _md("Table 3. Provisioning Time and Elasticity Velocity", h3, r3),
          _md("Table 5. Worked SEI Computation (Eq. 3; cost index derived from sourced pricing)", h5, r5)]
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "tables.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(md))
    print("Wrote outputs/tables.md and table*.csv")
    print("\n".join(md))


if __name__ == "__main__":
    main()
